--
-- PostgreSQL database dump
--

\restrict Ve8bvLcLdiUYnUnr7nQddACxjP1KBGIu8M5wF1SxseUC7blO6nWuIGasdEFgtEg

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: job_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_tags (
    job_id bigint NOT NULL,
    tag character varying(255)
);


ALTER TABLE public.job_tags OWNER TO postgres;

--
-- Name: jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    description_html text,
    job_page_url character varying(255) NOT NULL,
    labor_function character varying(255),
    location character varying(255),
    logo_url character varying(255),
    organization_title character varying(255),
    organization_url character varying(255),
    position_name character varying(255),
    posted_date_timestamp bigint NOT NULL
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: job_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_tags (job_id, tag) FROM stdin;
4	Media Production
4	Social Media Marketing
4	Project Management
4	Project Collaboration
5	Leadership
5	Agile Software Development
3	Media Production
5	Kanban Principles
5	Engineering Management
3	Video Editing
3	Project Management
3	Project Collaboration
5	Software Development
6	Data Analysis
6	SQL (Programming Language)
6	Python (Programming Language)
6	R (Programming Language)
6	Data Mining
6	Data Cleansing
5	Collaboration
6	Business Acumen
6	Communication Skills
6	Collaboration
7	Interaction Design
7	Visual Design
7	Figma (Design Software)
7	Adobe Creative Suite
7	User Interface Design
7	Communication Skills
9	Account Management
8	Project Management
7	Collaboration
9	Operational Excellence
9	Strategic Leadership
8	Interpersonal Communications
8	Problem Solving
9	Negotiation
8	Teamwork
8	Detail Oriented
10	Account Management
9	Problem Solving
9	Relationship Management
10	Operational Excellence
10	Strategic Leadership
9	Stakeholder Management
9	Business Acumen
10	E-Commerce
9	Communication Skills
10	Retail Sales
10	New Business Development
12	Campaign Management
12	Analytical Thinking
12	Problem Solving
12	Interpersonal Communications
12	Team Management
13	Account Management
10	Negotiation
13	Operational Excellence
13	Strategic Leadership
11	Account Management
13	E-Commerce
11	Operational Excellence
10	Problem Solving
13	New Business Development
10	Stakeholder Management
11	Strategic Leadership
10	Analytical Thinking
11	E-Commerce
11	Retail Sales
11	New Business Development
13	Market Analysis
10	Business Acumen
11	Negotiation
11	Problem Solving
11	Stakeholder Management
11	Analytical Thinking
11	Business Acumen
13	Negotiation
13	Relationship Management
13	Problem Solving
11	Entrepreneurship
10	Entrepreneurship
11	Communication Skills
10	Communication Skills
15	Tax Compliance
14	Operations Management
15	Transfer Pricing
14	Strategic Thinking
15	Tax Planning
14	Business Analytics
14	Accounting & Finance
15	International Taxation
14	Supply Chain Management
14	Interpersonal Communications
15	Analytical Thinking
14	Problem Solving
14	Decision Making
15	Communication Skills
14	Empowerment
15	Project Management
14	Empathy
16	Data Analysis
16	Business Intelligence
16	SQL (Programming Language)
16	Interpersonal Communications
16	Time Management
16	Problem Solving
16	E-Commerce
16	Information Technology
19	Product Design
18	Marketing Strategies
19	User Experience Design (UX)
19	Devtools
19	Systems Design
18	Relationship Building
18	Go-to-Market Strategy
19	User Analysis
18	Communication Skills
19	Prototyping
19	User Interface Design
19	Design Elements And Principles
20	Product Design
20	User Analysis
20	Prototyping
20	Usability Testing
20	User-Centered Design
20	Technical Acumen
20	Industry Analysis
20	Collaboration
20	Technical Documentation
20	Conversational AI
\.


--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jobs (id, description_html, job_page_url, labor_function, location, logo_url, organization_title, organization_url, position_name, posted_date_timestamp) FROM stdin;
2		https://wellfound.com/company/mosaicmfg/jobs/3367671-senior-fp-a-analyst	Software Engineering	Toronto, ON, Canada, Remote	https://cdn.getro.com/companies/d6d20055-4832-5cdb-b0df-3816c0f4c6eb-1746495325	Mosaic Manufacturing	\N	Senior FP&A Analyst	1755229196
8		https://www.lazada.com/en/careers/job-description/GP300635004	Software Engineering	Malaysia	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Analyst-Campaigns (2)	1755183956
11		https://www.lazada.com/en/careers/job-description/GP300555008	Software Engineering	Philippines	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Key Account Manager - FMCG (Beauty)-BGC	1755183956
17		https://climatebase.org/job/61073125/aiml-engineering-lead?source=company_page&queryID=f218b48855fdfb2192fd1cb35d9dac47	Software Engineering	Remote	https://cdn.getro.com/companies/cfeaad38-d2eb-5c9e-9fe8-631a3843edd1-1748137102	Climatize	\N	AI/ML Engineering Lead	1755182818
3		https://apply.workable.com/joinblink/j/CB7FF2D9A4	Software Engineering	London, UK	https://cdn.getro.com/companies/022f02dc-dcc5-5059-a769-a462498aefde-1748914565	Blink	\N	Video & social content creator	1755231289
7		https://www.lazada.com/en/careers/job-description/GP300049602	Software Engineering	Thailand	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	User Interface Designer-channel design	1755183957
12		https://www.lazada.com/en/careers/job-description/GP300635002	Software Engineering	Singapore	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Marketing Solutions - Operations Associate-Marketing Solutions	1755183956
15		https://www.lazada.com/en/careers/job-description/GP300555009	Software Engineering	Indonesia	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Senior Manager, Tax-Jakarta	1755183955
20		https://jobs.ashbyhq.com/rasa/59d7daa2-35ee-4465-a71b-83d215d2ce83	Software Engineering	Germany, Remote, United Kingdom	https://cdn.getro.com/companies/c8f86493-9b58-5e35-8678-b16d000eb1aa-1747532086	Rasa	\N	Senior Product Designer	1755179056
4		https://apply.workable.com/joinblink/j/8A67E36A77	Software Engineering	Boston, MA, USA	https://cdn.getro.com/companies/022f02dc-dcc5-5059-a769-a462498aefde-1748914565	Blink	\N	Marketing & video content creator	1755231290
6		https://www.lazada.com/en/careers/job-description/GP300555007	Software Engineering	China	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Category Strategy & Key Assortment BI-Hangzhou	1755183956
9		https://www.lazada.com/en/careers/job-description/GP300595008	Software Engineering	Philippines	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Key Account Manager - General Merchandise (Motors)-BGC	1755183956
14		https://www.lazada.com/en/careers/job-description/GP300555010	Software Engineering	Philippines	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Supervisor-San Pedro Sortation	1755183955
19		https://jobs.ashbyhq.com/stream/247b17f0-9c83-4fc9-a6ee-e9c45509727a	Software Engineering	Boulder, CO, USA, Remote	https://cdn.getro.com/companies/c0ec6d84-d829-5284-bc9e-7d66003be6a8-1748914604	Stream	\N	Staff Product Designer	1755180933
1		https://wellfound.com/company/certa-2/jobs/2903432-senior-cloud-infrastructure-engineer	Software Engineering	India, Remote	https://cdn.getro.com/companies/c6ccd082-f299-5a99-b245-e2e5a626737f-1747618192	Certa	\N	Senior Cloud Infrastructure Engineer	1755230284
10		https://www.lazada.com/en/careers/job-description/GP300595007	Software Engineering	Philippines	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Key Account Manager - Fashion (Women and Kids)-BGC	1755183956
18		https://jobs.ashbyhq.com/base-operations/0a7a4239-02ed-427e-9d5b-e64622e83c1a	Software Engineering	Washington, DC, USA	https://cdn.getro.com/companies/25c3256e-480a-5b7c-86cf-b32b03c47706-1748914856	Base Operations	\N	Director of Federal Sales	1755181800
5		https://apply.workable.com/joinblink/j/35271B5B04	Software Engineering	London, UK	https://cdn.getro.com/companies/022f02dc-dcc5-5059-a769-a462498aefde-1748914565	Blink	\N	Engineering Manager	1755231291
13		https://www.lazada.com/en/careers/job-description/GP300595009	Software Engineering	Philippines	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Key Account Manager - FMCG (Groceries & Pet Supplies)-BGC	1755183956
16		https://www.lazada.com/en/careers/job-description/GP300635007	Software Engineering	China	https://cdn.getro.com/companies/a5425cc9-9c52-5eea-ad89-40093d11b64c-1748914570	Drive Spotter	\N	Campaign BI-Hangzhou	1755183954
\.


--
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jobs_id_seq', 20, true);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: jobs ukq7cskiy7v0mwh660teqw09pj1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT ukq7cskiy7v0mwh660teqw09pj1 UNIQUE (job_page_url);


--
-- Name: job_tags fky5ln7dquha6f0a63bnux2qlk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_tags
    ADD CONSTRAINT fky5ln7dquha6f0a63bnux2qlk FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Ve8bvLcLdiUYnUnr7nQddACxjP1KBGIu8M5wF1SxseUC7blO6nWuIGasdEFgtEg

